from __future__ import annotations

SCHEDULE_CONTRACT: dict[str, dict] = {
    "activity_code": {
        "required": True,
        "type": "string",
        "semantic_role": "identifier",
        "aliases": [
            "activity_code",
            "activity code",
            "activity id",
            "activity_id",
            "activity no",
            "activity number",
            "activity no.",
            "activity number",
            "code",
            "task id",
            "task code",
            "task no",
            "task number",
            "job id",
            "item id",
            "schedule id",
            "activity reference",
            "activity ref",
        ],
        "positive_terms": [
            "code",
            "id",
            "identifier",
            "number",
            "no",
            "ref",
            "reference",
        ],
        "negative_terms": [
            "name",
            "title",
            "description",
            "desc",
            "scope",
            "responsible",
            "contractor",
            "company",
            "discipline",
            "status",
            "duration",
            "progress",
            "percent",
            "date",
        ],
    },

    "activity_name": {
        "required": True,
        "type": "string",
        "semantic_role": "description",
        "aliases": [
            "activity_name",
            "activity name",
            "activity",
            "description",
            "activity description",
            "discription",
            "activity title",
            "activity description",
            "discription",
            "task name",
            "task description",
            "task",
            "work description",
            "work item",
            "work package",
            "task title",
            "job description",
            "scope description",
            "scope of work",
        ],
        "positive_terms": [
            "name",
            "title",
            "description",
            "desc",
            "scope",
            "work",
            "task",
            "activity",
        ],
        "negative_terms": [
            "code",
            "id",
            "identifier",
            "number",
            "status",
            "duration",
            "progress",
            "percent",
            "start",
            "finish",
            "end",
            "date",
            "responsible",
            "contractor",
            "company",
            "discipline",
        ],
    },

    "wbs_id": {
        "required": False,
        "type": "integer",
        "semantic_role": "hierarchy",
        "aliases": [
            "wbs_id",
            "wbs id",
            "wbs",
            "wbs code",
            "wbs cod",
            "wbs_code",
            "wbs number",
            "wbs no",
            "wbs item",
            "work breakdown structure",
            "work breakdown",
        ],
        "positive_terms": [
            "wbs",
            "breakdown",
            "hierarchy",
            "structure",
        ],
        "negative_terms": [
            "activity",
            "task",
            "duration",
            "progress",
            "status",
        ],
    },

    "duration_days": {
        "required": False,
        "type": "integer",
        "semantic_role": "duration",
        "aliases": [
            "duration_days",
            "duration days",
            "duration/days",
            "duration days",
            "duration",
            "duration day",
            "days",
            "planned duration",
            "original duration",
            "planned days",
            "number of days",
            "working days",
            "calendar days",
            "total duration",
        ],
        "positive_terms": [
            "duration",
            "days",
            "day",
        ],
        "negative_terms": [
            "date",
            "start",
            "finish",
            "progress",
            "percent",
            "status",
        ],
    },

    "progress_percent": {
        "required": False,
        "type": "float",
        "semantic_role": "progress",
        "aliases": [
            "progress_percent",
            "progress percent",
            "progress",
            "% complete",
            "percent complete",
            "percentage complete",
            "completion",
            "completed %",
            "actual %",
            "actual progress",
            "actual completion",
            "physical progress",
            "physical completion",
            "progress %",
        ],
        "positive_terms": [
            "progress",
            "complete",
            "completion",
            "percent",
            "%",
            "actual",
        ],
        "negative_terms": [
            "status",
            "date",
            "duration",
            "code",
            "id",
        ],
    },

    "status": {
        "required": False,
        "type": "string",
        "semantic_role": "status",
        "aliases": [
            "status",
            "activity status",
            "current status",
            "task status",
            "state",
            "current state",
            "activity state",
            "task state",
        ],
        "positive_terms": [
            "status",
            "state",
        ],
        "negative_terms": [
            "progress",
            "complete",
            "date",
            "duration",
            "code",
            "id",
        ],
    },

    "start_date": {
        "required": False,
        "type": "date",
        "semantic_role": "date_start",
        "aliases": [
            "start_date",
            "start date",
            "start",
            "planned start",
            "planned start date",
            "baseline start",
            "commencement date",
            "begin date",
            "beginning date",
            "actual start",
            "forecast start",
        ],
        "positive_terms": [
            "start",
            "begin",
            "commencement",
            "planned",
            "baseline",
            "actual",
            "forecast",
        ],
        "negative_terms": [
            "finish",
            "end",
            "duration",
            "progress",
        ],
    },

    "finish_date": {
        "required": False,
        "type": "date",
        "semantic_role": "date_finish",
        "aliases": [
            "finish_date",
            "finish date",
            "finish",
            "end",
            "end date",
            "planned finish",
            "planned finish date",
            "baseline finish",
            "completion date",
            "actual finish",
            "forecast finish",
        ],
        "positive_terms": [
            "finish",
            "end",
            "completion",
            "planned",
            "baseline",
            "actual",
            "forecast",
        ],
        "negative_terms": [
            "start",
            "begin",
            "duration",
            "progress",
        ],
    },

    "responsible_party": {
        "required": False,
        "type": "string",
        "semantic_role": "responsibility",
        "aliases": [
            "contractor / responsible party",
            "contractor responsible party",
            "responsible contractor",
            "responsible_party",
            "responsible party",
            "responsible",
            "responsibility",
            "contractor",
            "subcontractor",
            "company",
            "discipline",
            "owner",
            "assigned to",
            "assigned",
            "responsible organization",
            "responsible company",
            "executing party",
            "performing organization",
        ],
        "positive_terms": [
            "responsible",
            "responsibility",
            "contractor",
            "subcontractor",
            "company",
            "discipline",
            "owner",
            "assigned",
            "organization",
            "party",
        ],
        "negative_terms": [
            "activity",
            "task",
            "description",
            "status",
            "duration",
            "progress",
            "date",
        ],
    },
}


REQUIRED_FIELDS: list[str] = [
    field
    for field, definition in SCHEDULE_CONTRACT.items()
    if definition["required"]
]


OPTIONAL_FIELDS: list[str] = [
    field
    for field, definition in SCHEDULE_CONTRACT.items()
    if not definition["required"]
]


