from __future__ import annotations

SCHEDULE_CONTRACT: dict[str, dict] = {
    "activity_code": {
        "required": True,
        "type": "string",
        "semantic_role": "identifier",
        "aliases": [
            "activity_code",
            "activity code",
            "activity id",
            "activity_id",
            "activity no",
            "activity number",
            "activity no.",
            "activity number",
            "code",
            "task id",
            "task code",
            "task no",
            "task number",
            "job id",
            "item id",
            "schedule id",
            "activity reference",
            "activity ref",
        ],
        "positive_terms": [
            "code",
            "id",
            "identifier",
            "number",
            "no",
            "ref",
            "reference",
        ],
        "negative_terms": [
            "name",
            "title",
            "description",
            "desc",
            "scope",
            "responsible",
            "contractor",
            "company",
            "discipline",
            "status",
            "duration",
            "progress",
            "percent",
            "date",
        ],
    },

    "activity_name": {
        "required": True,
        "type": "string",
        "semantic_role": "description",
        "aliases": [
            "activity_name",
            "activity name",
            "activity",
            "description",
            "activity description",
            "discription",
            "activity title",
            "activity description",
            "discription",
            "task name",
            "task description",
            "task",
            "work description",
            "work item",
            "work package",
            "task title",
            "job description",
            "scope description",
            "scope of work",
        ],
        "positive_terms": [
            "name",
            "title",
            "description",
            "desc",
            "scope",
            "work",
            "task",
            "activity",
        ],
        "negative_terms": [
            "code",
            "id",
            "identifier",
            "number",
            "status",
            "duration",
            "progress",
            "percent",
            "start",
            "finish",
            "end",
            "date",
            "responsible",
            "contractor",
            "company",
            "discipline",
        ],
    },

    "wbs_code": {
        "required": False,
        "type": "string",
        "semantic_role": "hierarchy_identifier",
        "aliases": [
            "wbs_code",
            "wbs code",
            "wbs cod",
            "wbs_id",
            "wbs id",
            "wbs",
            "wbs number",
            "wbs no",
            "work breakdown structure code",
            "work breakdown code",
        ],
        "positive_terms": [
            "wbs",
            "breakdown",
            "hierarchy",
            "structure",
            "code",
            "id",
            "number",
        ],
        "negative_terms": [
            "name",
            "title",
            "description",
            "activity",
            "task",
            "duration",
            "progress",
            "status",
        ],
    },

    "wbs_name": {
        "required": False,
        "type": "string",
        "semantic_role": "hierarchy_description",
        "aliases": [
            "wbs_name",
            "wbs name",
            "wbs title",
            "wbs description",
            "work package name",
            "work package title",
            "work breakdown structure name",
        ],
        "positive_terms": [
            "wbs",
            "breakdown",
            "hierarchy",
            "structure",
            "name",
            "title",
            "description",
        ],
        "negative_terms": [
            "code",
            "id",
            "number",
            "activity",
            "task",
            "duration",
            "progress",
            "status",
        ],
    },

    "duration_days": {
        "required": False,
        "type": "integer",
        "semantic_role": "duration",
        "aliases": [
            "duration_days",
            "duration days",
            "duration/days",
            "duration days",
            "duration",
            "duration day",
            "days",
            "planned duration",
            "original duration",
            "planned days",
            "number of days",
            "working days",
            "calendar days",
            "total duration",
        ],
        "positive_terms": [
            "duration",
            "days",
            "day",
        ],
        "negative_terms": [
            "date",
            "start",
            "finish",
            "progress",
            "percent",
            "status",
        ],
    },

    "progress_percent": {
        "required": False,
        "type": "float",
        "semantic_role": "progress",
        "aliases": [
            "progress_percent",
            "progress percent",
            "progress",
            "% complete",
            "percent complete",
            "percentage complete",
            "completion",
            "completed %",
            "actual %",
            "actual progress",
            "actual completion",
            "physical progress",
            "physical completion",
            "progress %",
        ],
        "positive_terms": [
            "progress",
            "complete",
            "completion",
            "percent",
            "%",
            "actual",
        ],
        "negative_terms": [
            "status",
            "date",
            "duration",
            "code",
            "id",
        ],
    },

    "status": {
        "required": False,
        "type": "string",
        "semantic_role": "status",
        "aliases": [
            "status",
            "activity status",
            "current status",
            "task status",
            "state",
            "current state",
            "activity state",
            "task state",
        ],
        "positive_terms": [
            "status",
            "state",
        ],
        "negative_terms": [
            "progress",
            "complete",
            "date",
            "duration",
            "code",
            "id",
        ],
    },

    "start_date": {
        "required": False,
        "type": "date",
        "semantic_role": "date_start",
        "aliases": [
            "start_date",
            "start date",
            "start",
            "planned start",
            "planned start date",
            "baseline start",
            "commencement date",
            "begin date",
            "beginning date",
            "actual start",
            "forecast start",
        ],
        "positive_terms": [
            "start",
            "begin",
            "commencement",
            "planned",
            "baseline",
            "actual",
            "forecast",
        ],
        "negative_terms": [
            "finish",
            "end",
            "duration",
            "progress",
        ],
    },

    "finish_date": {
        "required": False,
        "type": "date",
        "semantic_role": "date_finish",
        "aliases": [
            "finish_date",
            "finish date",
            "finish",
            "end",
            "end date",
            "planned finish",
            "planned finish date",
            "baseline finish",
            "completion date",
            "actual finish",
            "forecast finish",
        ],
        "positive_terms": [
            "finish",
            "end",
            "completion",
            "planned",
            "baseline",
            "actual",
            "forecast",
        ],
        "negative_terms": [
            "start",
            "begin",
            "duration",
            "progress",
        ],
    },

    "responsible_party": {
        "required": False,
        "type": "string",
        "semantic_role": "responsibility",
        "aliases": [
            "contractor / responsible party",
            "contractor responsible party",
            "responsible contractor",
            "responsible_party",
            "responsible party",
            "responsible",
            "responsibility",
            "contractor",
            "subcontractor",
            "company",
            "discipline",
            "owner",
            "assigned to",
            "assigned",
            "responsible organization",
            "responsible company",
            "executing party",
            "performing organization",
        ],
        "positive_terms": [
            "responsible",
            "responsibility",
            "contractor",
            "subcontractor",
            "company",
            "discipline",
            "owner",
            "assigned",
            "organization",
            "party",
        ],
        "negative_terms": [
            "activity",
            "task",
            "description",
            "status",
            "duration",
            "progress",
            "date",
        ],
    },
    "budgeted_cost": {
        "required": False,
        "type": "float",
        "semantic_role": "cost_budget",
        "aliases": [
            "budgeted_cost",
            "budgeted cost",
            "budget cost",
            "planned cost",
            "planned value",
            "bcws",
            "budget at completion",
            "budgeted total cost",
            "original budget",
            "baseline cost",
            "budget",
        ],
        "positive_terms": [
            "budget",
            "budgeted",
            "planned",
            "baseline",
            "bcws",
            "cost",
        ],
        "negative_terms": [
            "actual",
            "earned",
            "acwp",
            "bcwp",
            "variance",
            "progress",
            "percent",
            "date",
        ],
    },

    "actual_cost": {
        "required": False,
        "type": "float",
        "semantic_role": "cost_actual",
        "aliases": [
            "actual_cost",
            "actual cost",
            "acwp",
            "actual total cost",
            "cost to date",
            "spent cost",
            "actual expenditure",
            "actual spend",
        ],
        "positive_terms": [
            "actual",
            "spent",
            "spend",
            "acwp",
            "expenditure",
            "cost",
        ],
        "negative_terms": [
            "budget",
            "budgeted",
            "planned",
            "baseline",
            "earned",
            "bcwp",
            "bcws",
            "progress",
            "percent",
            "date",
        ],
    },

    "earned_value": {
        "required": False,
        "type": "float",
        "semantic_role": "cost_earned",
        "aliases": [
            "earned_value",
            "earned value",
            "bcwp",
            "earned cost",
            "value earned",
            "earned total value",
        ],
        "positive_terms": [
            "earned",
            "bcwp",
            "value",
        ],
        "negative_terms": [
            "budget",
            "budgeted",
            "planned",
            "baseline",
            "actual",
            "acwp",
            "bcws",
            "progress",
            "percent",
            "date",
        ],
    },

}


REQUIRED_FIELDS: list[str] = [
    field
    for field, definition in SCHEDULE_CONTRACT.items()
    if definition["required"]
]


OPTIONAL_FIELDS: list[str] = [
    field
    for field, definition in SCHEDULE_CONTRACT.items()
    if not definition["required"]
]


